POST http://localhost:8080/products
Content-Type: application/json


   [
        {
        "product_name": "Hydrolife",
        "product_type": "dizzy-water",
        "description": "Helps to digest after heavy dinner!",
        "category": "food",
        "brand": "Waterly"
        }
   ]