POST https://localhost:8080/products
Content-Type: application/json


   [
        {
        "product_name": "Kefir",
        "product_type": "dairy",
        "description": "Don`t eat your dumplings without me!",
        "category": "food",
        "brand": "Milky"
        }
   ]